config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, :only => [:show]
  resources :events
  resources :signups, :only => [:create, :destroy]

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :signups, foreign_key: :attended_event_id
  has_many :attendees, through: :signups, source: :event_attendee
  belongs_to :host, class_name: 'User'

  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 15 }
  validates :location, presence: true
  validates :date, presence: true, future: true

  scope :upcoming, -> { where('date >= ?', DateTime.now).order(:date) }
  scope :past, -> { where('date < ?', DateTime.now).order(:date) }
end

app/models/signup.rb
class Signup < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true, length: { in: 4..14 }
  validates :email, presence: true, uniqueness: true

  has_many :signups, foreign_key: :event_attendee_id
  has_many :attended_events, through: :signups
  has_many :hosted_events, foreign_key: :host_id, class_name: 'Event'
end

app/models/validators/future_validator.rb
class FutureValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if !record[attribute].nil? && record[attribute] < Time.now
      record.errors[attribute] << (options[:message] || "can't be in the past!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @events = Event.all
  end

  def show
    @signup = Signup.new
  end

  def new
    @event = current_user.hosted_events.build
  end

  def edit
  end

  def create
    @event = current_user.hosted_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Your event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Your event was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location, :description, :private)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  
  def create
    @signup = Signup.new
    @signup.event_attendee_id = params[:signup][:event_attendee_id]
    @signup.attended_event_id = params[:signup][:attended_event_id]

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup.attended_event, notice: "You have joined the event." }
        format.json { render :show, status: :created, location: @signup.attended_event }
      else
        format.html { redirect_to @signup.attended_event, status: :unprocessable_entity }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @signup = Signup.find(params[:id])
    @event = @signup.attended_event
    @signup.destroy

    redirect_to @event
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_cards.html.erb
<div class="column is-one-third">
  <div class="card">
    <div class="card-image">
      <%= link_to event do %>
        <figure class="image is-2by1">
          <img src="https://bulma.io/images/placeholders/640x320.png" alt="Placeholder image">
        </figure>
      <% end %>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <%= link_to event do %>
                <strong class="title is-4"><%= event.name %></strong>
              <% end %>
              <br>
              <%= event.date.try(:strftime, ("%-d/%-m/%y %H:%M")) %>
              <br><br>
              <%= truncate event.description, length: 100 %>
              <br>
              <small>
                <span class="icon no-pad"><i class="fas fa-user" aria-hidden="true"></i>&nbsp;</span><%= event.host.name %> · 
                <span class="icon no-pad"><i class="fas fa-map-marker-alt" aria-hidden="true"></i></span>
                <% if !user_signed_in? || (current_user.attended_events.include?(event) || event.host==current_user || event.private==false) %>
                  <%= event.location %>
                <% else %>
                  Private
                <% end %>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event, defaults: { required: false }) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :host_id, :value => current_user.id %> 
  <div class="field">
    <div class="control">
      <%= f.input :name, label: "Name", input_html: { class: "input" }, wrapper: false, label_html: 
        { class: "label" }, autofocus: true %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :date, label: "Date", as: :datetime, html5: true, include_blank: true, wrapper: false,
      label_html: { class: "label" }, input_html: { class: "input" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :location, label: "Location", input_html: { class: "input" }, wrapper: false, label_html: 
        { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :description, label: "Description", input_html: { class: "textarea" }, wrapper: false, label_html: 
        { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="checkbox">
      <%= f.input :private, label: "Set as private", input_html: { class: "checkbox" }, wrapper: false, label_html: 
        { class: "label" } %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/events/_past_list.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title is-2">
      Past Events
    </p>
    <p class="subtitle">
      Did you make it to one of these awesome celebrations?
    </p>
  </div>
</section>
<div class="columns is-multiline">
  <% if Event.past.any? %>
    <% Event.past.each do |event| %>
      <%= render 'cards', event: event %>
    <% end %>
  <% else %>
    <p class="pad-left">Nothing here. 😔 Checkout some upcoming events!</p>
  <% end %>
</div>

app/views/events/_upcoming_list.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title is-2">
      Upcoming Events
    </p>
    <p class="subtitle">
      Find something fun happening near you!
    </p>
  </div>
</section>
<div class="columns is-multiline">
  <% if Event.upcoming.any? %>
    <% Event.upcoming.each do |event| %>
      <%= render 'cards', event: event %>
    <% end %>
  <% else %>
    <p class="pad-left">No upcoming events. Why not <%= link_to "create one?", new_event_path %></p>
  <% end %>
</div>

app/views/events/edit.html.erb
<section class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
        <div class="box">
          <h1 class="title">Edit Event</h1>
          <%= render 'form', event: @event %>
        </div>
			</div>
		</div>
	</div>

  <nav class="navbar-end">
    <div class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'Cancel', events_path, class: "button is-dark" %>
          </p>
      </div>
    </div>
  </nav>
</section>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <%= render 'upcoming_list' %>
    <%= render 'past_list' %>
  </div>
</section>

app/views/events/new.html.erb
<section class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new event</h1>
					<%= render 'form', event: @event %>
			</div>
		</div>
	</div>

	<nav class="navbar-end">
		<div class="navbar-menu">
			<div class="navbar-item">
				<div class="field is-grouped">
					<p class="control">
						<%= link_to 'Canel', events_path, class: "button is-dark" %>
					</p>
			</div>
		</div>
	</nav>
</section>

app/views/events/show.html.erb
<section class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-two-thirds">
        <div class="card">
          <div class="card-image">
            <figure class="image image is-3by1">
              <img src="https://bulma.io/images/placeholders/720x240.png">
            </figure>
          </div>
          <div class="card-content">
            <% if current_user == @event.host %>
              <nav class="level">
                <h1 class="title is-2 tight-bottom"><%= @event.name %></h1>
                <div class="level-right is-mobile">
                  <%= link_to edit_event_path(@event), class: "level-item" do %>
                    <span class="icon"><i class="fa fa-pencil-alt" aria-hidden="true"></i></span>
                  <% end %>
                  <%= link_to @event, method: :delete, data: { confirm: "Are you sure you want to delete your event?" } do %>
                    <span class="icon"><i class="far fa-trash-alt" aria-hidden="true"></i></span>
                  <% end %>
                </div>
              </nav>
            <% else %>
              <h1 class="title is-2"><%= @event.name %></h1>
            <% end %>
            <div class="media">
              <div class="media-content">
                <label class="label">About this event</label>
                <p><%= simple_format(@event.description) %></p>
                <br>
                <p class="control">
                  <% if !user_signed_in? %>
                    <p><%= link_to 'Sign up', new_user_registration_path%> or <%= link_to 'sign in', 
                      new_user_session_path %> to join this event!</p>
                  <% elsif @event.host == current_user %>
                    <p class="has-text-primary">You are hosting this event! 🎉</p>
                  <% elsif current_user.attended_events.include?(@event) %>
                    <p class="has-text-primary">You are attending this event! 🎉</p>
                    <br>
                    <% current_signup = Signup.where(event_attendee_id: current_user, attended_event_id: @event) %>
                    <%= link_to current_signup.first, method: :delete, class: "button is-info", data: { confirm: 'Are you sure?' } do %>
                      <span class="icon"><i class="fas fa-calendar-minus"></i></span>
                      <span>Cancel reservation</span>
                    <% end %>
                  <% elsif @event.private == true %>
                    <p class="has-text-primary">This is a private event. 🤫</p>
                  <% else %>
                    <%= simple_form_for(@signup) do |f| %>
                      <%= f.hidden_field :event_attendee_id, :value => current_user.id %>
                      <%= f.hidden_field :attended_event_id, :value => @event.id %>
                      <%= button_tag type: 'submit', class: "button is-info" do %>
                        <span class="icon"><i class="fas fa-calendar-plus"></i></span>
                        <p>Join event</p>
                      <% end %>
                    <% end %>
                  <% end %>
                </p>
              </div>
              <div class="media-right">
                <p><label class="label">Hosted by</label><%= @event.host.name %></p>
                <br>
                <p>
                  <label class="label">Date and time</label>
                  <% if !user_signed_in? || (current_user.attended_events.include?(@event) || @event.host==current_user || @event.private==false) %>
                    <%= @event.date.try(:strftime, ("%-d/%-m/%y %H:%M")) %>
                  <% else %>
                    <p class="has-text-primary">- Private -</p>
                  <% end %>
                </p>
                <br>
                <p>
                  <label class="label">Location</label>
                  <% if !user_signed_in? || (current_user.attended_events.include?(@event) || @event.host==current_user || @event.private==false) %>
                    <%= @event.location %>
                  <% else %>
                    <p class="has-text-primary">- Private -</p>
                  <% end %>
                </p>
              </div>
            </div>
          </article>
        </div>
			</div>
      <br>
      <div class="card">
        <% if @event.attendees.any? %>
          <div class="card-content">
            <div class="content is-medium tight-bottom"><strong>Attendee List</strong></div>
            <div class="content">
              <div class="columns is-multiline">
                <div class="column is-two-thirds">
                  <ul>
                    <% @event.attendees.each do |attendee| %>
                      <li><%= attendee.name %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div class="card-content">
            <div class="content is-medium"><strong>Attendee List</strong></div>
            <% if current_user == @event.host %>
              <p>No one has signed up to your event yet. 😔 Time to share with friends!</p>
            <% else %>
              <p>No one has signed up to this event yet. 😔 Be the first!</p>
            <% end %>
          </div>
        <% end %>
      </div>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      Created by <a href="https://github.com/gregolive" target="_blank">gregolive</a>.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-primary">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item logo" do %>
      <%= image_tag "logo.png", alt: "Eventive logo" %>&nbsp;
    <% end %>
    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to new_event_url, class: "button is-info is-inverted" do %>
                <span class="icon">
                  <i class="far fa-calendar-plus"></i>
                </span>
                <span>Create an event</span>
              <% end %>
            </p>
            <p class="control">
              <%= link_to current_user, class: "button is-primary" do %>
                <span class="icon">
                  <i class="fas fa-user"></i>
                </span>
                <span>u/<%= current_user.username %></span>
              <% end %>
            </p>
            <p class="control">
              <%= link_to destroy_user_session_path, method: :delete, class: "button is-primary" do %>
                <span class="icon">
                  <i class="fas fa-sign-out-alt"></i>
                </span>
                <span>Logout</span>
              <% end %>
            </p>
          <% else %>
            <p class="control">
              <%= link_to new_user_registration_path, class: "button is-info is-inverted" do %>
                <span class="icon">
                  <i class="fas fa-user-plus"></i>
                </span>
                <span>Sign up</span>
              <% end %>
            </p>
            <p class="control">
              <%= link_to new_user_session_path, class: "button is-primary" do %>
                <span class="icon">
                  <i class="fas fa-sign-in-alt"></i>
                </span>
                <span>Sign in</span>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-mutate-approach="sync"></script>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body class="flex-wrapper">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_events.html.erb
<div class="column is-one-third">
  <div class="card">
    <div class="card-image">
      <%= link_to event do %>
        <figure class="image is-2by1">
          <img src="https://bulma.io/images/placeholders/640x320.png" alt="Placeholder image">
        </figure>
      <% end %>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <%= link_to event do %>
                <strong class="title is-5"><%= event.name %></strong>
              <% end %>
              <br>
              <%= truncate event.description, length: 100 %>
              <br>
              <small><%= event.location %> · <%= event.date.try(:strftime, ("%-d/%-m/%y %H:%M")) %></small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">
    <% if Time.now.hour.between?(4,12) %>
      Good morning,
    <% elsif Time.now.hour.between?(12,17) %>
      Good afternoon,
    <% elsif Time.now.hour > 17 || Time.now.hour < 4 %>
      Good evening,
    <% else %>
      Hello,
    <% end %>
    <%= @user.name %> 👋</h2>
    <br>
    <p><%= link_to edit_user_registration_path do %>
      <span class="icon">
        <i class="fas fa-user-edit"></i>
      </span>
      Edit account information
    <% end %></p>
    <br>
    <% future_host_events = @user.hosted_events.where('date >= ?', Date.today).order(:date) %>
    <h4 class="title is-4">Events you are hosting</h4>
    <div class="columns is-multiline">
      <% if future_host_events.any? %>
        <% future_host_events.each do |event| %>
          <%= render 'events', event: event %>
        <% end %>
      <% else %>
        <p class="column is-one-third">You are not hosting any upcoming events. <%= link_to "Create one now!", new_event_path %></p>
      <% end %>
    </div>
    <br>
    <% future_attend_events = @user.attended_events.where('date >= ?', Date.today).order(:date) %>
    <h4 class="title is-4">Events you are attending</h4>
    <div class="columns is-multiline">
      <% if future_attend_events.any? %>
        <% future_attend_events.each do |event| %>
          <%= render 'events', event: event %>
        <% end %>
      <% else %>
        <p class="column is-one-third">You are not attending any upcoming events. <%= link_to "Find one now!", events_path %></p>
      <% end %>
    </div>
    <br>
    <% past_events = @user.hosted_events.where('date < ?', Date.today).order(:date) + @user.attended_events.where('date < ?', Date.today).order(:date) %>
    <h4 class="title is-4">Past events</h4>
    <div class="columns is-left">
      <% if past_events.any? %>
        <% past_events.each do |event| %>
          <%= render 'events', event: event %>
        <% end %>
      <% else %>
        <p class="column is-one-third">You haven't hosted or attended any events yet.</p>
      <% end %>
    </div>
  </div>
</section>